spring:
  datasource:
    url: jdbc:h2:mem:spaceshipdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=100,expireAfterWrite=10m


server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.jordicunillerarivera.spaceship.aspect: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"